### ISSUE TITLE
Can you submit the `libsimpleservo.so` you compiled? Thank you

### ISSUE THREAD

**Issue by westinyang** [jschwe/ServoDemo#1]
I don't know what environment variables `source ohos.env` specifically configures. Can you submit the `libsimpleservo.so` you compiled? Thank you

**Comment by jschwe** [comment]
I'm currently working on upstreaming my changes into the main servo repository. As part of that I'll also update the building instructions in the next few days (hopefully). Perhaps we can make the `.so` available for download as an artifact from the nightly build of servos CI.

**Comment by westinyang** [comment]
Ok thanks

**Comment by westinyang** [comment]
Could you send me the product libservoshell.so built by Servo before the completion of the CI automatic build? I want to do some tests locally. I'm a freelance developer and have also done many open source projects related to OpenHarmony. If possible, please send it to this email address: westinyang@qq.com. Thank you.

**Comment by jschwe** [comment]
@westinyang I created a release in this repo and attached a  pre-compiled `.so` for arm64 ohos. See https://github.com/jschwe/ServoDemo/releases/tag/v0.0.1

I also improved the Readme of this repository with updated instructions how to build.
Now it is actually quite easy to build `libservoshell.so` - you just need to 
1. Have the OpenHarmony SDK installed on Linux or MacOS (Windows is not supported due to a bug in the ohos SDK for windows)
2. clone the servo project
3. configure the `.servobuild` file according to the Readme, so `./mach` knows where to find the ohos SDK.
4. Run `./mach build --target=aarch64-unknown-linux-ohos --release`

And thats it - The libservoshell.so will be in the folder `target/aarch64-unknown-linux-ohos/release`
